#!/usr/bin/env python3
"""
Apply monthly verification updates to Supabase.

Expected input is the narrow CSV from prepare_monthly_verification_updates.py,
for example august_supabase_updates.csv.
"""

import argparse
import os
import sys
from datetime import datetime
from typing import Any, Dict

import pandas as pd


def current_last_verified() -> str:
    """Return today's date in MM/DD/YY last_verified format."""
    return datetime.now().strftime("%m/%d/%y")


def clean_value(value: Any):
    if pd.isna(value):
        return None
    text = str(value).strip()
    if text.lower() in {"", "nan", "none", "null"}:
        return None
    return text


def response_status_from_payload(payload: Dict[str, Any]):
    """Find the monthly verification status value in an update payload."""
    for column, value in payload.items():
        if column.endswith("_verification_status"):
            return value
    return None


def main():
    parser = argparse.ArgumentParser(description="Apply monthly verification CSV updates to Supabase")
    parser.add_argument("updates_csv", help="CSV generated by prepare_monthly_verification_updates.py")
    parser.add_argument("--table", default="open_mics_historical")
    parser.add_argument(
        "--last-verified",
        default=current_last_verified(),
        help="Value to write to last_verified for every applied row. Defaults to today's MM/DD/YY.",
    )
    parser.add_argument(
        "--preserve-last-verified",
        action="store_true",
        help="Use last_verified values from the CSV instead of stamping every row with --last-verified.",
    )
    parser.add_argument("--apply", action="store_true", help="Actually write updates. Without this, runs as a dry run.")
    args = parser.parse_args()

    updates = pd.read_csv(args.updates_csv, dtype=str, keep_default_na=False)
    if "unique_identifier" not in updates.columns:
        print("❌ updates_csv must include unique_identifier")
        sys.exit(1)

    rows = []
    for _, row in updates.iterrows():
        mic_id = clean_value(row.get("unique_identifier"))
        if not mic_id:
            continue

        payload: Dict[str, Any] = {}
        for column, value in row.items():
            if column == "unique_identifier":
                continue
            if column == "last_verified" and not args.preserve_last_verified:
                continue
            cleaned = clean_value(value)
            if cleaned is not None:
                payload[column] = cleaned

        has_non_date_update = any(column != "last_verified" for column in payload)
        response_status = response_status_from_payload(payload)
        should_stamp_last_verified = response_status in {"responded_confirmed", "responded_changes"}
        if should_stamp_last_verified and not args.preserve_last_verified:
            payload["last_verified"] = args.last_verified

        if has_non_date_update or args.preserve_last_verified:
            rows.append((mic_id, payload))

    print("=" * 70)
    print("MONTHLY VERIFICATION SUPABASE UPDATE")
    print("=" * 70)
    print(f"Input file: {args.updates_csv}")
    print(f"last_verified mode: {'CSV values' if args.preserve_last_verified else args.last_verified}")
    print(f"Rows with update payloads: {len(rows)}")

    if not args.apply:
        print("\nDry run only. Add --apply to write these updates to Supabase.")
        for mic_id, payload in rows[:5]:
            print(f"- {mic_id}: {payload}")
        if len(rows) > 5:
            print(f"... and {len(rows) - 5} more")
        return

    from dotenv import load_dotenv
    from supabase import Client, create_client

    load_dotenv()
    url = os.environ.get("SUPABASE_URL")
    key = os.environ.get("SUPABASE_KEY")
    if not url or not key:
        print("❌ Missing SUPABASE_URL or SUPABASE_KEY in .env")
        sys.exit(1)

    supabase: Client = create_client(url, key)
    updated = 0
    for mic_id, payload in rows:
        supabase.table(args.table).update(payload).eq("unique_identifier", mic_id).execute()
        updated += 1

    print(f"\n✅ Updated {updated} rows in {args.table}")
    print("=" * 70)


if __name__ == "__main__":
    main()
